// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2tvA-TSMH0SAHCAX-VTxOYSs48Rfh1HM',
    appId: '1:121572106936:web:8773838b5d1985297e0a4d',
    messagingSenderId: '121572106936',
    projectId: 'sajilo-ride-85fd9',
    authDomain: 'sajilo-ride-85fd9.firebaseapp.com',
    storageBucket: 'sajilo-ride-85fd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1l9EqWZaPfcK99jhcigzUTTFbW_e2Qcs',
    appId: '1:121572106936:android:b717d16287aa1e767e0a4d',
    messagingSenderId: '121572106936',
    projectId: 'sajilo-ride-85fd9',
    storageBucket: 'sajilo-ride-85fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI28Fy9Y46xCNiGOEwdvrWTRqy5uhIO0g',
    appId: '1:121572106936:ios:fef9c35a611096177e0a4d',
    messagingSenderId: '121572106936',
    projectId: 'sajilo-ride-85fd9',
    storageBucket: 'sajilo-ride-85fd9.firebasestorage.app',
    iosBundleId: 'com.example.sajiloRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI28Fy9Y46xCNiGOEwdvrWTRqy5uhIO0g',
    appId: '1:121572106936:ios:fef9c35a611096177e0a4d',
    messagingSenderId: '121572106936',
    projectId: 'sajilo-ride-85fd9',
    storageBucket: 'sajilo-ride-85fd9.firebasestorage.app',
    iosBundleId: 'com.example.sajiloRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2tvA-TSMH0SAHCAX-VTxOYSs48Rfh1HM',
    appId: '1:121572106936:web:5e07a00858ba11dc7e0a4d',
    messagingSenderId: '121572106936',
    projectId: 'sajilo-ride-85fd9',
    authDomain: 'sajilo-ride-85fd9.firebaseapp.com',
    storageBucket: 'sajilo-ride-85fd9.firebasestorage.app',
  );
}
